# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 595d87f4f679fbc01cbd42ddbc462d217dd786db730bf1082634032765c22a2878cd66d4e1d867b5c5e19d66d5ad86432f87803f22362c8daaf2ccca0e96f865

test:
  secret_key_base: ffcfdfd9f654fbe891a5b55b00915c51c6d58825cb0a61b38bdf061c8c9017d356765d0042958d503762607dc2ca4cc256722cd773c65ecb8dfb2ebda6836308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
